using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace SmartPlant.Models
{
    public class SensorData
    {
        [Key] //autogenerated id by DB
        [JsonIgnore]
        public int id { get; set; }

        //foreign key PlantID
        [ForeignKey("Plant"), Required]
        public string PlantID { get; set; }
        [JsonIgnore]
        public virtual Plant Plant { get; set; }

        [Display(Name = "Temperature")]
        [Column("Temperature")] //celsius
        [Range(-30,50) ,Required]
        public int Temp { get; set; }

        //percentage value? decimal(5,2)
        //store its if less precision ok?
        [Range(0,100) ,Required]
        public int Humidity { get; set; }

        //Integer value? measure in lux?
        [Range(0, 100), Required]
        public int LightIntensity { get; set; }

        //percentage value ? use integer if less precision is fine.
        [Display(Name = "Moisture %")]
        [Column("Moisture %")]
        [Range(0, 100), Required]
        public int Moisture { get; set; }

        //timestamp for when these values were recorded
        //datetime2
        //UTC        
        [Required]
        public DateTime TimeStampUTC { get; set; }

    }
}
